### ISSUE TITLE
Functions not bindable

### ISSUE THREAD

**Issue by eronskhan** [BioPhoton/ionic1-star-rating#5]
Currently using ionic1-star-rating in a ionic1 javascript project and I cannot seem to get any of my custom functions to work with the component.
By custom functions, I mean functions passed to any of the following properties;
 getColor / getHalfStarVisible / onClick / onRatingChange / onHover

Closing this as I discovered a hole in my testsuite.

**Comment by BioPhoton** [comment]
Hi. Nice that you were able to solve it.

The custom functions should be tested in angular 1-star-rating which this lib extends from.

If I could improve the docs just give me the right hint.
