### ISSUE TITLE
Color property is not working

### ISSUE THREAD

**Issue by mohammed-alsiddeeq** [BioPhoton/ionic1-star-rating#7]
When setting the color property  to any of the possible values it does not change
```html
<!-- Nothing happens-->
<star-rating-comp rating="3" color="'ok'" ></star-rating-comp>
```

**Comment by BioPhoton** [comment]
In your case you have to use the [] or remoe the ''.

**Comment by BioPhoton** [comment]
Hope it helps!

**Comment by mohammed-alsiddeeq** [comment]
No, it didn't work
> In your case you have to use the [] or remoe the ''.  

tried both but no luck.
Thanks for your time though, much appreciated

**Comment by mohammed-alsiddeeq** [comment]
I took a look at the source code
Actually it is `static-color`
Now it is working
Thanks @BioPhoton
